apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mqceu3e6n-nodejs 
  janus-idp.io/tekton: mqceu3e6n-nodejs
  backstage.io/kubernetes-id: mqceu3e6n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqceu3e6n-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml