apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mqceu3e6n-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mqceu3e6n-nodejs-gitops